CREATE TABLE GM_GDP
(CountryName VARCHAR(40),
Year INTEGER NOT NULL,
GDP NUMERIC,
CONSTRAINT GM_GDPKey PRIMARY KEY (CountryName, Year));

CREATE TABLE GM_EU
(CountryName VARCHAR(40),
Year INTEGER NOT NULL,
EU NUMERIC,
CONSTRAINT GM_EUKey PRIMARY KEY (CountryName, Year));

CREATE TABLE GM_LE
(CountryName VARCHAR(40),
Year INTEGER NOT NULL,
LE NUMERIC,
CONSTRAINT GM_LEKey PRIMARY KEY (CountryName, Year));

CREATE TABLE GM_HS
(CountryName VARCHAR(40),
Year INTEGER NOT NULL,
HS NUMERIC,
CONSTRAINT GM_HSKey PRIMARY KEY (CountryName, Year));

CREATE TABLE GM_POP
(CountryName VARCHAR(40),
Year INTEGER NOT NULL,
POP NUMERIC,
CONSTRAINT GM_POPKey PRIMARY KEY (CountryName, Year));